In [5]:
import pandas as pd
df = pd.read_csv("../dataset/raw/occupancy.csv")
df

,time,102,104,105,106,107,108,109,110,111,...,1156,1159,1162,1163,1164,1166,1167,1168,1172,1173
0,2022-09-01 00:00:00,17.0,1.0,15.0,54.0,23.0,13.0,11.0,6.0,20.0,...,10.0,31.0,9.0,2.0,45.0,26.0,183.0,17.0,2.0,10.0
1,2022-09-01 01:00:00,16.0,1.0,19.0,50.0,25.0,13.0,7.0,12.0,19.0,...,7.0,31.0,8.0,1.0,42.0,25.0,174.0,12.0,2.0,9.0
2,2022-09-01 02:00:00,16.0,1.0,20.0,44.0,24.0,16.0,12.0,6.0,21.0,...,7.0,38.0,9.0,2.0,48.0,24.0,196.0,13.0,2.0,12.0
3,2022-09-01 03:00:00,16.0,1.0,20.0,44.0,22.0,16.0,12.0,6.0,21.0,...,7.0,38.0,9.0,2.0,48.0,24.0,187.0,13.0,2.0,13.0
4,2022-09-01 04:00:00,17.0,1.0,20.0,50.0,24.0,13.0,8.0,12.0,20.0,...,7.0,31.0,8.0,1.0,42.0,25.0,167.0,11.0,2.0,10.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4339,2023-02-28 19:00:00,10.0,2.0,15.0,43.0,13.0,12.0,6.0,9.0,12.0,...,4.0,37.0,2.0,5.0,33.0,22.0,145.0,8.0,3.0,9.0
4340,2023-02-28 20:00:00,13.0,2.0,16.0,43.0,16.0,14.0,8.0,9.0,13.0,...,4.0,38.0,3.0,5.0,30.0,23.0,171.0,10.0,4.0,10.0
4341,2023-02-28 21:00:00,14.0,2.0,16.0,44.0,18.0,13.0,7.0,10.0,14.0,...,3.0,36.0,7.0,5.0,34.0,27.0,183.0,10.0,4.0,10.0
4342,2023-02-28 22:00:00,14.0,2.0,18.0,45.0,18.0,13.0,7.0,11.0,15.0,...,3.0,35.0,8.0,4.0,35.0,29.0,197.0,10.0,4.0,10.0
4343,2023-02-28 23:00:00,14.0,2.0,20.0,45.0,18.0,13.0,8.0,12.0,15.0,...,3.0,36.0,9.0,4.0,35.0,31.0,201.0,11.0,4.0,11.0

In [2]:
df.shape

(4344, 276)

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4344 entries, 0 to 4343
Columns: 276 entries, time to 1173
dtypes: float64(275), object(1)
memory usage: 9.1+ MB

In [11]:
occupancy_long = df.melt(
    id_vars=["time"],
    var_name="zone",
    value_name="occupancy"
)

occupancy_long.head()

                  time zone  occupancy
0  2022-09-01 00:00:00  102       17.0
1  2022-09-01 01:00:00  102       16.0
2  2022-09-01 02:00:00  102       16.0
3  2022-09-01 03:00:00  102       16.0
4  2022-09-01 04:00:00  102       17.0

In [12]:
occupancy_long.shape

(1194600, 3)

In [13]:
occupancy_long.isnull().sum()

time         0
zone         0
occupancy    0
dtype: int64

In [14]:
zone_avg = (
    occupancy_long
    .groupby("zone")["occupancy"]
    .mean()
    .sort_values(ascending=False)
)

zone_avg.head(10)

zone
1167    137.304558
526     102.887891
519      87.164825
1011     82.056860
703      80.162178
335      76.468692
1049     74.671961
633      70.684162
851      65.610497
1068     64.189572
Name: occupancy, dtype: float64

In [15]:
occupancy_long["occupancy"].describe()

count    1.194600e+06
mean     1.786646e+01
std      2.101456e+01
min      0.000000e+00
25%      5.000000e+00
50%      1.100000e+01
75%      2.300000e+01
max      3.730000e+02
Name: occupancy, dtype: float64

In [16]:
occupancy_long[occupancy_long["occupancy"]>100].head()

                       time zone  occupancy
96142   2022-09-24 22:00:00  217      115.0
97416   2022-11-17 00:00:00  217      114.0
127504  2022-11-03 16:00:00  307      102.0
184683  2022-12-03 03:00:00  329      102.0
184684  2022-12-03 04:00:00  329      102.0

In [17]:
zone_overload = (
    occupancy_long
    .assign(overload=occupancy_long["occupancy"] > 100)
    .groupby("zone")["overload"]
    .mean()
    .sort_values(ascending=False)
)

zone_overload.head(10)

zone
1167    0.763582
526     0.546731
519     0.407919
1049    0.279466
703     0.184392
1011    0.132597
851     0.094843
633     0.033610
335     0.027855
595     0.022330
Name: overload, dtype: float64